/*
 * Part of Opace Preferred Source Checker. Reusable module — no Chrome APIs,
 * no external dependencies. Also consumed by Essential SEO Toolkit.
 * Module version: 1.0.0
 *
 * psl-lite: curated subset of the Public Suffix List adequate for apex
 * detection on the overwhelming majority of real sites. Generated by hand
 * from the live PSL, 26 August 2026. Swapping in the full PSL is a drop-in
 * change confined to this module. Where an unknown ccTLD second-level
 * suffix misclassifies, the worst outcome is the E1/E2 wording choice —
 * never a wrong deeplink for ordinary commercial sites (see spec §10).
 */

const TWO_LABEL_PUBLIC_SUFFIXES = new Set([
  // .uk
  'co.uk', 'com.uk', 'org.uk', 'net.uk', 'gov.uk', 'ac.uk', 'edu.uk',
  'sch.uk', 'mil.uk', 'police.uk', 'nhs.uk', 'me.uk', 'ltd.uk', 'plc.uk',
  // .au
  'com.au', 'net.au', 'org.au', 'gov.au', 'edu.au', 'asn.au', 'id.au',
  // .jp
  'co.jp', 'ne.jp', 'or.jp', 'go.jp', 'ac.jp', 'ad.jp', 'ed.jp', 'gr.jp', 'lg.jp',
  // .nz
  'co.nz', 'org.nz', 'net.nz', 'ac.nz', 'govt.nz', 'gov.nz', 'school.nz', 'geek.nz', 'maori.nz',
  // .mx
  'com.mx', 'net.mx', 'org.mx', 'gob.mx', 'edu.mx',
  // .br
  'com.br', 'net.br', 'org.br', 'gov.br', 'edu.br',
  // .in
  'co.in', 'com.in', 'org.in', 'net.in', 'gov.in', 'edu.in', 'ac.in',
  'res.in', 'gen.in', 'firm.in', 'ind.in', 'nic.in',
  // .za
  'co.za', 'org.za', 'net.za', 'gov.za', 'edu.za', 'ac.za', 'web.za',
  // .sg
  'com.sg', 'net.sg', 'org.sg', 'gov.sg', 'edu.sg', 'per.sg',
  // .hk
  'com.hk', 'net.hk', 'org.hk', 'gov.hk', 'edu.hk', 'idv.hk',
  // .tr
  'com.tr', 'net.tr', 'org.tr', 'gov.tr', 'edu.tr', 'k12.tr', 'av.tr',
  'bel.tr', 'pol.tr', 'web.tr', 'gen.tr',
  // .pl
  'com.pl', 'net.pl', 'org.pl', 'gov.pl', 'edu.pl', 'info.pl', 'biz.pl', 'waw.pl',
  // .il
  'co.il', 'org.il', 'net.il', 'gov.il', 'ac.il', 'muni.il', 'k12.il',
  // .kr
  'co.kr', 'ne.kr', 'or.kr', 'go.kr', 'ac.kr', 're.kr', 'pe.kr', 'hs.kr', 'ms.kr', 'es.kr',
  // .cn
  'com.cn', 'net.cn', 'org.cn', 'gov.cn', 'edu.cn', 'ac.cn',
  // .tw
  'com.tw', 'net.tw', 'org.tw', 'gov.tw', 'edu.tw', 'idv.tw', 'game.tw', 'club.tw',
  // .ar
  'com.ar', 'net.ar', 'org.ar', 'gob.ar', 'gov.ar', 'edu.ar', 'int.ar', 'mil.ar',
  // .id
  'co.id', 'net.id', 'or.id', 'go.id', 'ac.id', 'web.id', 'sch.id', 'my.id', 'biz.id',
  // .th
  'co.th', 'net.th', 'or.th', 'go.th', 'ac.th', 'in.th', 'mi.th',
  // .my
  'com.my', 'net.my', 'org.my', 'gov.my', 'edu.my', 'mil.my', 'name.my',
  // .ph
  'com.ph', 'net.ph', 'org.ph', 'gov.ph', 'edu.ph', 'ngo.ph', 'mil.ph', 'i.ph',
  // .ke
  'co.ke', 'or.ke', 'ne.ke', 'go.ke', 'ac.ke', 'sc.ke', 'info.ke', 'me.ke', 'mobi.ke',
  // .ng
  'com.ng', 'net.ng', 'org.ng', 'gov.ng', 'edu.ng', 'name.ng', 'sch.ng', 'mobi.ng', 'i.ng',
  // .eg
  'com.eg', 'net.eg', 'org.eg', 'gov.eg', 'edu.eg', 'sci.eg', 'eun.eg', 'name.eg',
  // .sa
  'com.sa', 'net.sa', 'org.sa', 'gov.sa', 'edu.sa', 'med.sa', 'sch.sa', 'pub.sa',
  // .ae
  'co.ae', 'com.ae', 'net.ae', 'org.ae', 'gov.ae', 'ac.ae', 'sch.ae', 'mil.ae'
  // Private-registry suffixes (blogspot.com style) deliberately excluded —
  // treated as normal domains per spec §10.
]);

/**
 * Compute the registrable domain (eTLD+1) for a lowercase hostname.
 * Single-label hosts and IP addresses must be handled by the caller first.
 * Algorithm (spec §10): if the last two labels form a known public suffix,
 * the registrable domain is the last three labels; otherwise the last two.
 *
 * @param {string} host lowercase hostname, no trailing dot
 * @returns {string|null} registrable domain, or null when not computable
 */
export function getRegistrableDomain(host) {
  if (typeof host !== 'string' || host.length === 0) return null;
  const labels = host.split('.');
  if (labels.length < 2) return null;
  const lastTwo = labels.slice(-2).join('.');
  if (TWO_LABEL_PUBLIC_SUFFIXES.has(lastTwo)) {
    if (labels.length < 3) return null; // host IS a public suffix
    return labels.slice(-3).join('.');
  }
  return lastTwo;
}

export { TWO_LABEL_PUBLIC_SUFFIXES };
